apiVersion: v1 # the version of api
kind: PersistentVolume
metadata:
  namespace: lw
  name: my-pv
  labels:
    app: web
spec:
  accessModes:
  - ReadWriteOnce
  capacity: 
    storage: 1Gi
  hostPath: 
    path: /new_dir/

