apiVersion: v1 # the version in which that resource is present.
kind: Pod # the kind of resource we are going to create.
metadata:
  name: sql-pod
  labels:
    env: dev
    app: db
spec:
  containers:
  - name: sql-con
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306

