apiVersion: v1 # api Version in which the resource is present.
kind: Service # the type of Resource to create
metadata:
   name: sql-client-ip
   labels:
     env: dev
     app: sql-wp-app
spec:
  selector:
    app: db
    env: dev
  type: NodePort #type of Service to be used.
  ports:
  - targetPort: 3306 # mysql service port
    port: 3306

